AWSTemplateFormatVersion: "2010-09-09"
Description: Sample database stack for the Parameters section
Resources:
  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-051da6bba7830955b
      GroupDescription: "Database instances security group"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 3306
          ToPort: 3306
          IpProtocol: tcp

  DbSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: Subnets to launch db instances into
      SubnetIds:
        - subnet-04deef4edca825c07
        - subnet-0fe8b8e0937bfd21a
        - subnet-049305cc90efbb3fc

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t2.micro
      Engine: mariadb
      MultiAZ: false
      PubliclyAccessible: true
      AllocatedStorage: "8"
      MasterUsername: dbadmin
      MasterUserPassword: "12345678"
      DBSubnetGroupName: !Ref DbSubnetGroup
      VPCSecurityGroups:
        - !Ref DbSecurityGroup
